//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public Area()
        {
            this.Sugerencia = new HashSet<Sugerencia>();
            this.Empleado = new HashSet<Empleado>();
            this.ProcedimientoAuditoria = new HashSet<ProcedimientoAuditoria>();
            this.ProcedimientoSeguimiento = new HashSet<ProcedimientoSeguimiento>();
        }
    
        public int Co_Area { get; set; }
        public string No_Area { get; set; }
        public string Tx_Descripcion { get; set; }
        public string Tx_Responsable { get; set; }
    
        public virtual ICollection<Sugerencia> Sugerencia { get; set; }
        public virtual ICollection<Empleado> Empleado { get; set; }
        public virtual ICollection<ProcedimientoAuditoria> ProcedimientoAuditoria { get; set; }
        public virtual ICollection<ProcedimientoSeguimiento> ProcedimientoSeguimiento { get; set; }
    }
}
