//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materia
    {
        public Materia()
        {
            this.ProcedimientoAuditoria = new HashSet<ProcedimientoAuditoria>();
            this.ProcedimientoSeguimiento = new HashSet<ProcedimientoSeguimiento>();
        }
    
        public int IDMateria { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<ProcedimientoAuditoria> ProcedimientoAuditoria { get; set; }
        public virtual ICollection<ProcedimientoSeguimiento> ProcedimientoSeguimiento { get; set; }
    }
}
