//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reclamo_Poliza
    {
        public int Co_ReclamoPoliza { get; set; }
        public string Fi_Estado { get; set; }
        public Nullable<int> Co_Poliza { get; set; }
        public string Nu_Reclamo { get; set; }
    
        public virtual Poliza Poliza { get; set; }
        public virtual Reclamo Reclamo { get; set; }
    }
}
