//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public Area()
        {
            this.Sugerencias = new HashSet<Sugerencia>();
            this.Empleadoes = new HashSet<Empleado>();
            this.ProcedimientoAuditorias = new HashSet<ProcedimientoAuditoria>();
            this.ProcedimientoSeguimientoes = new HashSet<ProcedimientoSeguimiento>();
        }
    
        public int Co_Area { get; set; }
        public string No_Area { get; set; }
        public string Tx_Descripcion { get; set; }
        public string Tx_Responsable { get; set; }
    
        public virtual ICollection<Sugerencia> Sugerencias { get; set; }
        public virtual ICollection<Empleado> Empleadoes { get; set; }
        public virtual ICollection<ProcedimientoAuditoria> ProcedimientoAuditorias { get; set; }
        public virtual ICollection<ProcedimientoSeguimiento> ProcedimientoSeguimientoes { get; set; }
    }
}
