//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Campania
    {
        public Campania()
        {
            this.Comision = new HashSet<Comision>();
        }
    
        public int Co_Campania { get; set; }
        public string No_Campania { get; set; }
        public System.DateTime Fe_Inicio { get; set; }
        public System.DateTime Fe_Fin { get; set; }
        public int Qt_Meta { get; set; }
        public bool Fl_Flag { get; set; }
    
        public virtual ICollection<Comision> Comision { get; set; }
    }
}
