//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CanalVenta
    {
        public CanalVenta()
        {
            this.Comisions = new HashSet<Comision>();
        }
    
        public int Cod_Cnl_Vta { get; set; }
        public string Nro_Cnl_Vta { get; set; }
        public string Txt_Tipo { get; set; }
    
        public virtual ICollection<Comision> Comisions { get; set; }
    }
}
