//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cargo
    {
        public Cargo()
        {
            this.Comision = new HashSet<Comision>();
            this.Empleado = new HashSet<Empleado>();
        }
    
        public int Cod_Car { get; set; }
        public string Nro_Car { get; set; }
    
        public virtual ICollection<Comision> Comision { get; set; }
        public virtual ICollection<Empleado> Empleado { get; set; }
    }
}
