//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cliente
    {
        public Cliente()
        {
            this.Poliza = new HashSet<Poliza>();
            this.Sugerencia = new HashSet<Sugerencia>();
            this.Sugerencia1 = new HashSet<Sugerencia>();
        }
    
        public int Co_Cliente { get; set; }
        public string No_Cliente { get; set; }
        public string No_ApePaterno { get; set; }
        public string No_ApeMaterno { get; set; }
        public bool Fi_Sexo { get; set; }
        public string Nu_DNI { get; set; }
        public System.DateTime Fe_Nacimiento { get; set; }
        public string Nu_Telefono { get; set; }
        public string Nu_Movil { get; set; }
        public string Tx_Direccion { get; set; }
        public string Tx_Correo { get; set; }
        public string Fi_EstadoCivil { get; set; }
        public string Tx_CentroTrabajo { get; set; }
        public string Tx_CargoTrabajo { get; set; }
        public string Tx_LugarNacimiento { get; set; }
    
        public virtual ICollection<Poliza> Poliza { get; set; }
        public virtual ICollection<Sugerencia> Sugerencia { get; set; }
        public virtual ICollection<Sugerencia> Sugerencia1 { get; set; }
    }
}
