//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departamento
    {
        public Departamento()
        {
            this.Provincias = new HashSet<Provincia>();
        }
    
        public int Co_Departamento { get; set; }
        public string No_Departamento { get; set; }
    
        public virtual ICollection<Provincia> Provincias { get; set; }
    }
}
