//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePropuestaSolucion
    {
        public int Co_DetallePropuestaSolucion { get; set; }
        public int Co_PropuestaSolucion { get; set; }
        public int Nu_Anio { get; set; }
        public int Nu_Edad { get; set; }
        public decimal Ss_MontoPrima { get; set; }
        public decimal Ss_MontoAhorro { get; set; }
        public decimal Ss_ValorRescate { get; set; }
        public decimal Ss_MontoAsegurado { get; set; }
    
        public virtual PropuestaSolucion PropuestaSolucion { get; set; }
    }
}
