//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePropuestaSolucion
    {
        public int Cod_Det_Prop_Sol { get; set; }
        public int Cod_Prop_Sol { get; set; }
        public int Num_Anio { get; set; }
        public int Num_Edad { get; set; }
        public decimal Ss_Mon_Prim { get; set; }
        public decimal Ss_Mon_Ahr { get; set; }
        public decimal Ss_Val_Resc { get; set; }
        public decimal Ss_Mon_Aseg { get; set; }
    
        public virtual PropuestaSolucion PropuestaSolucion { get; set; }
    }
}
