//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetallePropuestaSolucion
    {
        public int Co_DetallePropuestaSolucion { get; set; }
        public int Co_PropuestaSolucion { get; set; }
        public int Nu_Anio { get; set; }
        public int Nu_Edad { get; set; }
        public decimal Ss_MontoPrima { get; set; }
        public decimal Ss_MontoAhorro { get; set; }
        public decimal Ss_ValorRescate { get; set; }
        public decimal Ss_MontoAsegurado { get; set; }
    
        public virtual PropuestaSolucion PropuestaSolucion { get; set; }
    }
}
