//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distrito
    {
        public Distrito()
        {
            this.Reclamantes = new HashSet<Reclamante>();
            this.Empleadoes = new HashSet<Empleado>();
            this.Prestadoras = new HashSet<Prestadora>();
        }
    
        public int Co_Distrito { get; set; }
        public string No_Distrito { get; set; }
        public int Co_Provincia { get; set; }
    
        public virtual ICollection<Reclamante> Reclamantes { get; set; }
        public virtual Provincia Provincia { get; set; }
        public virtual ICollection<Empleado> Empleadoes { get; set; }
        public virtual ICollection<Prestadora> Prestadoras { get; set; }
    }
}
