//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Distrito
    {
        public Distrito()
        {
            this.Reclamante = new HashSet<Reclamante>();
            this.Empleado = new HashSet<Empleado>();
            this.Prestadora = new HashSet<Prestadora>();
        }
    
        public int Co_Distrito { get; set; }
        public string No_Distrito { get; set; }
        public int Co_Provincia { get; set; }
    
        public virtual ICollection<Reclamante> Reclamante { get; set; }
        public virtual Provincia Provincia { get; set; }
        public virtual ICollection<Empleado> Empleado { get; set; }
        public virtual ICollection<Prestadora> Prestadora { get; set; }
    }
}
