//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empleado
    {
        public int Co_Empleado { get; set; }
        public string No_Empleado { get; set; }
        public string No_ApePaterno { get; set; }
        public string No_ApeMaterno { get; set; }
        public bool Fl_Sexo { get; set; }
    }
}
