//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class FormatoPlanTrabajo
    {
        public int IDFormatoPlanTrabajo { get; set; }
        public int IDPlan { get; set; }
        public int IDPeriodo { get; set; }
        public string Descripcion { get; set; }
        public int IDResponsable { get; set; }
        public string Version { get; set; }
        public byte[] Adjunto { get; set; }
        public string Comentario { get; set; }
    
        public virtual Periodo Periodo { get; set; }
        public virtual PlanTrabajo PlanTrabajo { get; set; }
    }
}
