//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDPacificoEntities1 : DbContext
    {
        public BDPacificoEntities1()
            : base("name=BDPacificoEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Areas { get; set; }
        public virtual DbSet<Campania> Campanias { get; set; }
        public virtual DbSet<CanalVenta> CanalVentas { get; set; }
        public virtual DbSet<Cargo> Cargoes { get; set; }
        public virtual DbSet<Cliente> Clientes { get; set; }
        public virtual DbSet<Comision> Comisions { get; set; }
        public virtual DbSet<Departamento> Departamentoes { get; set; }
        public virtual DbSet<DetallePropuestaSolucion> DetallePropuestaSolucions { get; set; }
        public virtual DbSet<Distrito> Distritoes { get; set; }
        public virtual DbSet<Empleado> Empleadoes { get; set; }
        public virtual DbSet<Estado_Solicitud> Estado_Solicitud { get; set; }
        public virtual DbSet<FormatoPlanTrabajo> FormatoPlanTrabajoes { get; set; }
        public virtual DbSet<Invitacion> Invitacions { get; set; }
        public virtual DbSet<Materia> Materias { get; set; }
        public virtual DbSet<Periodo> Periodoes { get; set; }
        public virtual DbSet<PlanProducto> PlanProductoes { get; set; }
        public virtual DbSet<PlanTrabajo> PlanTrabajoes { get; set; }
        public virtual DbSet<Poliza> Polizas { get; set; }
        public virtual DbSet<Prestadora> Prestadoras { get; set; }
        public virtual DbSet<Procedimiento> Procedimientoes { get; set; }
        public virtual DbSet<ProcedimientoAuditoria> ProcedimientoAuditorias { get; set; }
        public virtual DbSet<ProcedimientoSeguimiento> ProcedimientoSeguimientoes { get; set; }
        public virtual DbSet<Producto> Productoes { get; set; }
        public virtual DbSet<PropuestaSolucion> PropuestaSolucions { get; set; }
        public virtual DbSet<Prospecto> Prospectoes { get; set; }
        public virtual DbSet<Provincia> Provincias { get; set; }
        public virtual DbSet<Rango> Rangoes { get; set; }
        public virtual DbSet<Reclamante> Reclamantes { get; set; }
        public virtual DbSet<Reclamo> Reclamoes { get; set; }
        public virtual DbSet<Reclamo_Motivo> Reclamo_Motivo { get; set; }
        public virtual DbSet<Reclamo_Poliza> Reclamo_Poliza { get; set; }
        public virtual DbSet<Requisito> Requisitoes { get; set; }
        public virtual DbSet<Solicitud_Afiliacion> Solicitud_Afiliacion { get; set; }
        public virtual DbSet<Solicitud_Autorizacion> Solicitud_Autorizacion { get; set; }
        public virtual DbSet<Sugerencia> Sugerencias { get; set; }
        public virtual DbSet<Tema> Temas { get; set; }
    }
}
