//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDPacificoEntities : DbContext
    {
        public BDPacificoEntities()
            : base("name=BDPacificoEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Area> Area { get; set; }
        public virtual DbSet<Campania> Campania { get; set; }
        public virtual DbSet<CanalVenta> CanalVenta { get; set; }
        public virtual DbSet<Cargo> Cargo { get; set; }
        public virtual DbSet<Cliente> Cliente { get; set; }
        public virtual DbSet<Comision> Comision { get; set; }
        public virtual DbSet<Departamento> Departamento { get; set; }
        public virtual DbSet<DetallePropuestaSolucion> DetallePropuestaSolucion { get; set; }
        public virtual DbSet<Distrito> Distrito { get; set; }
        public virtual DbSet<Empleado> Empleado { get; set; }
        public virtual DbSet<Estado_Solicitud> Estado_Solicitud { get; set; }
        public virtual DbSet<FormatoPlanTrabajo> FormatoPlanTrabajo { get; set; }
        public virtual DbSet<Invitacion> Invitacion { get; set; }
        public virtual DbSet<Materia> Materia { get; set; }
        public virtual DbSet<Periodo> Periodo { get; set; }
        public virtual DbSet<PlanProducto> PlanProducto { get; set; }
        public virtual DbSet<PlanTrabajo> PlanTrabajo { get; set; }
        public virtual DbSet<Poliza> Poliza { get; set; }
        public virtual DbSet<Prestadora> Prestadora { get; set; }
        public virtual DbSet<Procedimiento> Procedimiento { get; set; }
        public virtual DbSet<ProcedimientoAuditoria> ProcedimientoAuditoria { get; set; }
        public virtual DbSet<ProcedimientoSeguimiento> ProcedimientoSeguimiento { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<PropuestaSolucion> PropuestaSolucion { get; set; }
        public virtual DbSet<Prospecto> Prospecto { get; set; }
        public virtual DbSet<Provincia> Provincia { get; set; }
        public virtual DbSet<Rango> Rango { get; set; }
        public virtual DbSet<Reclamante> Reclamante { get; set; }
        public virtual DbSet<Reclamo> Reclamo { get; set; }
        public virtual DbSet<Reclamo_Motivo> Reclamo_Motivo { get; set; }
        public virtual DbSet<Reclamo_Poliza> Reclamo_Poliza { get; set; }
        public virtual DbSet<Requisito> Requisito { get; set; }
        public virtual DbSet<Solicitud_Afiliacion> Solicitud_Afiliacion { get; set; }
        public virtual DbSet<Solicitud_Autorizacion> Solicitud_Autorizacion { get; set; }
        public virtual DbSet<Sugerencia> Sugerencia { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tema> Tema { get; set; }
        public virtual DbSet<ComisionRequisito> ComisionRequisito { get; set; }
        public virtual DbSet<Visita> Visita { get; set; }
        public virtual DbSet<TipoVisita> TipoVisita { get; set; }
        public virtual DbSet<TipoPlan> TipoPlan { get; set; }
        public virtual DbSet<Beneficiario> Beneficiario { get; set; }
        public virtual DbSet<TipoPoliza> TipoPoliza { get; set; }
    }
}
