//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BDPacificoEntities1 : DbContext
    {
        public BDPacificoEntities1()
            : base("name=BDPacificoEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<PlanProducto> PlanProducto { get; set; }
        public virtual DbSet<Prospecto> Prospecto { get; set; }
        public virtual DbSet<Producto> Producto { get; set; }
        public virtual DbSet<DetallePropuestaSolucion> DetallePropuestaSolucion { get; set; }
        public virtual DbSet<PropuestaSolucion> PropuestaSolucion { get; set; }
    }
}
