//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Periodo
    {
        public Periodo()
        {
            this.FormatoPlanTrabajoes = new HashSet<FormatoPlanTrabajo>();
            this.PlanTrabajoes = new HashSet<PlanTrabajo>();
            this.ProcedimientoAuditorias = new HashSet<ProcedimientoAuditoria>();
            this.ProcedimientoSeguimientoes = new HashSet<ProcedimientoSeguimiento>();
        }
    
        public int IDPeriodo { get; set; }
        public string Descripcion { get; set; }
    
        public virtual ICollection<FormatoPlanTrabajo> FormatoPlanTrabajoes { get; set; }
        public virtual ICollection<PlanTrabajo> PlanTrabajoes { get; set; }
        public virtual ICollection<ProcedimientoAuditoria> ProcedimientoAuditorias { get; set; }
        public virtual ICollection<ProcedimientoSeguimiento> ProcedimientoSeguimientoes { get; set; }
    }
}
