//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanTrabajo
    {
        public PlanTrabajo()
        {
            this.FormatoPlanTrabajo = new HashSet<FormatoPlanTrabajo>();
        }
    
        public int IDPlan { get; set; }
        public int IDPeriodo { get; set; }
        public string Actividades { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public System.DateTime FechaFin { get; set; }
        public string Version { get; set; }
        public byte[] Adjunto { get; set; }
        public string Comentario { get; set; }
    
        public virtual ICollection<FormatoPlanTrabajo> FormatoPlanTrabajo { get; set; }
        public virtual Periodo Periodo { get; set; }
    }
}
