//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanProducto
    {
        public int Co_PlanProducto { get; set; }
        public string No_PlanProducto { get; set; }
        public decimal Ss_PrimaMinima { get; set; }
        public int Ss_SumaMinimaAsegurada { get; set; }
        public int Ss_SumaMaximaAsegurada { get; set; }
        public int Co_Producto { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
