//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlanProducto
    {
        public int Co_PlanProducto { get; set; }
        public string No_PlanProducto { get; set; }
        public decimal Ss_PrimaMinima { get; set; }
        public int Ss_SumaMinimaAsegurada { get; set; }
        public int Ss_SumaMaximaAsegurada { get; set; }
        public int Co_Producto { get; set; }
    
        public virtual Producto Producto { get; set; }
    }
}
