//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProcedimientoSeguimiento
    {
        public int IDProcedimientoSeguimiento { get; set; }
        public int IDPlan { get; set; }
        public int IDPeriodo { get; set; }
        public string EvaluacionVerificacion { get; set; }
        public System.DateTime FechaInicio { get; set; }
        public System.DateTime FechaFin { get; set; }
        public string TiempoEjecucion { get; set; }
        public int IDEmpleadoResponsable { get; set; }
        public int IDRepresentanteUnidad { get; set; }
        public int Co_Area { get; set; }
        public int IDMateria { get; set; }
        public string Comentario { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Empleado Empleado { get; set; }
        public virtual Empleado Empleado1 { get; set; }
        public virtual Materia Materia { get; set; }
        public virtual Periodo Periodo { get; set; }
    }
}
