//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.PlanProducto = new HashSet<PlanProducto>();
            this.PropuestaSolucion = new HashSet<PropuestaSolucion>();
        }
    
        public int Co_Producto { get; set; }
        public string No_Producto { get; set; }
        public System.DateTime Fe_Creacion { get; set; }
        public bool FI_Flag { get; set; }
    
        public virtual ICollection<PlanProducto> PlanProducto { get; set; }
        public virtual ICollection<PropuestaSolucion> PropuestaSolucion { get; set; }
    }
}
