//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producto
    {
        public Producto()
        {
            this.PlanProducto = new HashSet<PlanProducto>();
            this.PropuestaSolucion = new HashSet<PropuestaSolucion>();
        }
    
        public int Co_Producto { get; set; }
        public string No_Producto { get; set; }
        public System.DateTime Fe_Creacion { get; set; }
        public bool FI_Flag { get; set; }
    
        public virtual ICollection<PlanProducto> PlanProducto { get; set; }
        public virtual ICollection<PropuestaSolucion> PropuestaSolucion { get; set; }
    }
}
