//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PropuestaSolucion
    {
        public PropuestaSolucion()
        {
            this.DetallePropuestaSolucion = new HashSet<DetallePropuestaSolucion>();
        }
    
        public int Co_PropuestaSolucion { get; set; }
        public decimal Ss_MontoPrima { get; set; }
        public string Fe_Nacimiento { get; set; }
        public decimal Ss_MontoRetorno { get; set; }
        public decimal Ss_MontoAsegurado { get; set; }
        public int Co_Prospecto { get; set; }
        public int Co_Producto { get; set; }
        public int Co_Plan { get; set; }
        public System.DateTime Fe_Creacion { get; set; }
    
        public virtual ICollection<DetallePropuestaSolucion> DetallePropuestaSolucion { get; set; }
        public virtual Producto Producto { get; set; }
        public virtual Prospecto Prospecto { get; set; }
    }
}
