//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prospecto
    {
        public Prospecto()
        {
            this.PropuestaSolucions = new HashSet<PropuestaSolucion>();
        }
    
        public int Cod_Pros { get; set; }
        public string Txt_Pros { get; set; }
        public string Txt_Ape_Pat { get; set; }
        public string Txt_Ape_Mat { get; set; }
        public string Txt_Dir { get; set; }
        public string Txt_Tel { get; set; }
        public string Txt_Mov { get; set; }
        public string Txt_Crr { get; set; }
        public string Num_DNI { get; set; }
    
        public virtual ICollection<PropuestaSolucion> PropuestaSolucions { get; set; }
    }
}
