//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prospecto
    {
        public Prospecto()
        {
            this.PropuestaSolucion = new HashSet<PropuestaSolucion>();
        }
    
        public int Co_Prospecto { get; set; }
        public string No_Prospecto { get; set; }
        public string Tx_ApePaterno { get; set; }
        public string Tx_ApeMaterno { get; set; }
        public string Tx_Direccion { get; set; }
        public string Tx_Telefono { get; set; }
        public string Tx_Movil { get; set; }
        public string Tx_Correo { get; set; }
        public string Nu_DNI { get; set; }
    
        public virtual ICollection<PropuestaSolucion> PropuestaSolucion { get; set; }
    }
}
