//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Provincia
    {
        public Provincia()
        {
            this.Distritoes = new HashSet<Distrito>();
        }
    
        public int Co_Provincia { get; set; }
        public string No_Provincia { get; set; }
        public int Co_Departamento { get; set; }
    
        public virtual Departamento Departamento { get; set; }
        public virtual ICollection<Distrito> Distritoes { get; set; }
    }
}
