//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rango
    {
        public int Co_Rango { get; set; }
        public double Ss_Minimo { get; set; }
        public double Ss_Maximo { get; set; }
        public int Qt_Cantidad { get; set; }
        public int Co_Comision { get; set; }
    
        public virtual Comision Comision { get; set; }
    }
}
