//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reclamante
    {
        public Reclamante()
        {
            this.Reclamo = new HashSet<Reclamo>();
            this.Reclamo1 = new HashSet<Reclamo>();
        }
    
        public int Co_Reclamante { get; set; }
        public string No_Reclamante { get; set; }
        public string No_ApePaterno { get; set; }
        public string No_ApeMaterno { get; set; }
        public string Fi_Sexo { get; set; }
        public string Nu_DNI { get; set; }
        public Nullable<System.DateTime> Fe_Nacimiento { get; set; }
        public string Tx_Telefono { get; set; }
        public string Tx_Movil { get; set; }
        public string Tx_Correo { get; set; }
        public Nullable<int> Co_Distrito { get; set; }
        public string Tx_Direccion { get; set; }
    
        public virtual Distrito Distrito { get; set; }
        public virtual Distrito Distrito1 { get; set; }
        public virtual ICollection<Reclamo> Reclamo { get; set; }
        public virtual ICollection<Reclamo> Reclamo1 { get; set; }
    }
}
