//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud_Autorizacion
    {
        public int Co_Solicitud { get; set; }
        public int Co_Poliza { get; set; }
        public int Co_Sede { get; set; }
        public System.DateTime Fe_Solicitud { get; set; }
        public string No_Contacto { get; set; }
        public string No_ApePatContacto { get; set; }
        public string No_ApeMatContacto { get; set; }
        public string Nu_TelefonoContacto { get; set; }
        public string Tx_CorreoContacto { get; set; }
        public int Co_Procedimiento { get; set; }
        public decimal Ss_Monto { get; set; }
        public int Co_Evaluador { get; set; }
        public int Co_Autorizador { get; set; }
        public string Tx_ObservacionEvaluador { get; set; }
        public string Tx_ObservacionAutorizador { get; set; }
        public int Fl_Estado { get; set; }
        public System.DateTime Fe_RegistroIns { get; set; }
        public string No_UsuarioIns { get; set; }
        public System.DateTime Fe_RegistroUpd { get; set; }
        public string No_UsuarioUpd { get; set; }
    
        public virtual Empleado Empleado { get; set; }
        public virtual Empleado Empleado1 { get; set; }
    }
}
