//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sugerencia
    {
        public int Nu_Sugerencia { get; set; }
        public string Tx_Sugerencia { get; set; }
        public Nullable<System.DateTime> Fe_Registro { get; set; }
        public string Fi_Estado { get; set; }
        public Nullable<int> Co_Tema { get; set; }
        public Nullable<int> Co_Area { get; set; }
        public Nullable<int> Co_Cliente { get; set; }
    
        public virtual Area Area { get; set; }
        public virtual Area Area1 { get; set; }
        public virtual Cliente Cliente { get; set; }
        public virtual Cliente Cliente1 { get; set; }
        public virtual Tema Tema { get; set; }
        public virtual Tema Tema1 { get; set; }
    }
}
