//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pacifico.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TipoVisita
    {
        public TipoVisita()
        {
            this.Visita = new HashSet<Visita>();
        }
    
        public int Cod_Tipo_Visita { get; set; }
        public string Nro_Visita { get; set; }
    
        public virtual ICollection<Visita> Visita { get; set; }
    }
}
